let score = 0;
score = 10;
score += 1;
score += 10;
//let score = 2;
//scor;
let name = "Aurélien";
typeof(score);
typeof(name);
score = 0;
let points = 10;
score + points;
let greet = "Bonjour";
greet + name;
greet + " " + name;
let userInput = "2";
typeof(userInput);
userInput += 1;
userInput = "2.1";
let userInputInt = parseInt(userInput);
let userInputFloat = parseFloat(userInput);
